{
 "title": "Micronaut Executors",
 "tags": [
  "micronaut ",
  "executors"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Executor time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(executor_seconds_sum[5m]) / irate(executor_seconds_count[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Executor Active Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_active_threads{name=\"io\"}",
     "legendFormat": "IO Threads"
    },
    {
     "expr": "executor_active_threads{name=\"scheduled\"}",
     "legendFormat": "Scheduled Threads"
    }
   ]
  },
  {
   "title": "Completed Tasks Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "executor_completed_tasks_total", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Executor Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Remaining Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_queue_remaining_tasks", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "executor_queued_tasks", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Executor Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Core Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_pool_core_threads", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_pool_size_threads", "legendFormat": "{{name}}" }
   ]
  }
 ]
}